version: "3"
services:
    dev:
        image: golang:1.13
        volumes:
            - .:/work
        working_dir: /work
        depends_on:
            - schema-registry
    schema-registry:
        image: confluentinc/cp-schema-registry:5.5.1
        depends_on:
            - zookeeper
            - kafka
        environment:
            SCHEMA_REGISTRY_HOST_NAME: schema-registry
            SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
    kafka:
        image: confluentinc/cp-kafka:5.5.1
        depends_on:
            - zookeeper
        environment:
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    zookeeper:
        image: confluentinc/cp-zookeeper:5.5.1
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
